name: Test build

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check ENV VAR
      run: ruby test.rb
      env:
        HOSTING_USER: ${{secrets.HOSTING_USER}}
        TOMNATT_HOSTING_DIR: ${{secrets.TOMNATT_HOSTING_DIR}}
        DEPLOY_TARGET: ${{secrets.DEPLOY_TARGET}}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
